# Generated by Django 3.2.7 on 2021-10-26 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_no', models.CharField(default='', max_length=13)),
                ('items_json', models.CharField(default='', max_length=2500)),
            ],
        ),
        migrations.RemoveField(
            model_name='item',
            name='item_selected',
        ),
    ]
