# Generated by Django 3.2.7 on 2021-10-26 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avm', '0002_auto_20211026_1938'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='id',
        ),
        migrations.AddField(
            model_name='order',
            name='order_id',
            field=models.AutoField(default=True, primary_key=True, serialize=False),
        ),
    ]
